In [29]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [33]:
us_idx = pd.read_csv('US_indices.csv').T
us_idx.columns = us_idx.iloc[0]
us_idx = us_idx.iloc[1:]
us_idx 
%store us_idx

eu_idx = pd.read_csv('EU_indices.csv').T
eu_idx.columns = eu_idx.iloc[0]
eu_idx = eu_idx.iloc[1:]
eu_idx 
%store eu_idx

Stored 'us_idx' (DataFrame)
Stored 'eu_idx' (DataFrame)

In [34]:
tickers = pd.read_csv('Unique_List_With BBG ticker.csv')
tickers 
%store tickers

Stored 'tickers' (DataFrame)

In [22]:
#CONCATING ALL THE CSV FILES INTO ONE
df = pd.DataFrame()

for yr in range(1999, 2022):
    str_yr = str(yr)

    p_file_path = "Price/" + str_yr + '.csv'
    price_df = pd.read_csv(p_file_path, header = 0, index_col = 0, parse_dates=True, skiprows=4)
    price_df = price_df.T
    
#     v_file_path = "Volume/"  + str_yr + '.csv'
#     volume_df = pd.read_csv(v_file_path, header = 0, index_col = 0, parse_dates=True, skiprows=4)
#     volume_df = volume_df.T

#     pv_df[name + ' Volume'] = volume_df

    df = pd.concat([df, price_df])
df

Ticker,KRXX4N-R,P8R3C2-R,MH33D6-R,MCNYYL-R,M75WZB-R,KPK586-R,QLGSL2-R,HTM0LK-R,KV0J41-R,CSMTMQ-R,...,N6R7J4-R,R5ZYMX-R,JZKCL0-R,LX3YSB-R,N1TBJ8-R,KCDXY9-R,C36895-R,NPWT6Y-R,N5GP20-R,X9QX47-R
1/1/1999,NaN,34.671875,0.365513,53.541668,NaN,NaN,NaN,NaN,41.93750,40.71875,...,NaN,20.962967,NaN,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1/2/1999,NaN,34.671875,0.365513,53.541668,NaN,NaN,NaN,NaN,41.93750,40.71875,...,NaN,20.962967,NaN,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1/3/1999,NaN,34.671875,0.365513,53.541668,NaN,NaN,NaN,NaN,41.93750,40.71875,...,NaN,20.962967,NaN,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1/4/1999,NaN,35.250000,0.368304,59.156250,NaN,NaN,NaN,NaN,41.34375,40.31250,...,NaN,21.000000,NaN,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1/5/1999,NaN,36.625000,0.386719,62.250000,NaN,NaN,NaN,NaN,41.50000,40.62500,...,NaN,21.000000,NaN,290.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
05/26/2021,35.30,251.490000,126.850000,3265.160000,207.0,618.0,327.66,2380.31,169.07000,142.17000,...,NaN,44.800000,27.82,196.0,5.22,1.625,78.8,0.305,NaN,NaN
05/27/2021,35.25,249.310000,125.280000,3230.110000,208.8,605.5,332.75,2362.68,168.81000,141.69000,...,NaN,45.800000,28.46,195.0,5.28,1.650,80.1,0.305,NaN,NaN
05/28/2021,35.25,249.680000,124.610000,3223.070000,207.4,601.5,328.73,2356.85,169.25000,142.03000,...,NaN,45.600000,27.10,195.0,5.68,1.650,80.5,0.305,NaN,NaN
05/29/2021,35.25,249.680000,124.610000,3223.070000,207.4,601.5,328.73,2356.85,169.25000,142.03000,...,NaN,45.600000,27.10,195.0,5.68,1.650,80.5,0.305,NaN,NaN
05/30/2021,35.25,249.680000,124.610000,3223.070000,207.4,601.5,328.73,2356.85,169.25000,142.03000,...,NaN,45.600000,27.10,195.0,5.68,1.650,80.5,0.305,NaN,NaN

In [37]:
all_stocks_df = df
all_stocks_df.to_csv("All_Stocks.csv")

CPU times: user 2.3 s, sys: 440 ms, total: 2.74 s
Wall time: 3.03 s

,01/01/2001,01/02/2001,01/03/2001,01/04/2001,01/05/2001,01/06/2001,01/07/2001,01/08/2001,01/09/2001,01/10/2001,...,12/22/2001,12/23/2001,12/24/2001,12/25/2001,12/26/2001,12/27/2001,12/28/2001,12/29/2001,12/30/2001,12/31/2001
Ticker,,,,,,,,,,,,,,,,,,,,,
KRXX4N-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P8R3C2-R,21.687500,21.687500,23.968750,24.218750,24.562500,24.562500,24.562500,24.468750,25.90625,26.437500,...,33.770,33.770,33.635000,33.635000,33.84000,33.925000,33.935000,33.935000,33.935000,33.125000
MH33D6-R,0.265625,0.265625,0.292411,0.304688,0.292411,0.292411,0.292411,0.295759,0.30692,0.295759,...,0.375,0.375,0.381429,0.381429,0.38375,0.394107,0.400536,0.400536,0.400536,0.391071
MCNYYL-R,15.562500,13.875000,17.562500,15.500000,14.562500,14.562500,14.562500,14.937500,16.37500,16.500000,...,10.000,10.000,9.830000,9.830000,11.10000,10.600000,10.900000,10.900000,10.900000,10.820000
M75WZB-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KCDXY9-R,2.740000,2.675000,2.580000,2.660000,2.650000,2.650000,2.650000,2.640000,2.62500,2.650000,...,2.225,2.225,2.225000,2.225000,2.22500,2.225000,2.400000,2.400000,2.400000,2.500000
C36895-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NPWT6Y-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N5GP20-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X9QX47-R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN